DROP TABLE STOCKHOLM.CRIMES;
DROP TABLE STOCKHOLM.CRIMECATEGORY;
CREATE TABLE STOCKHOLM.CRIMECATEGORY(
ID INTEGER not null PRIMARY KEY,
CATEGORY VARCHAR(255),
ISRELEVANT VARCHAR(255)
);

INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (1,'Bedrägeri','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (2,'Olaga intrång','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (3,'Inbrott','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (4,'Misshandel','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (5,'Motorfordon','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (6,'Olaga hot','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (7,'Rån','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (8,'Skadegörelse','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (9,'Stöld','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (10,'Våldtäkt','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (11,'Bråk','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (12,'Olycka , olycksfall','N');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (13,'Försvunnen','N');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (14,'Trafikolycka','N');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (15,'Arbetsplatsolycka','N');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (16,'Brand','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (17,'Snatteri','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (18,'Narkotikabrott','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (19,'Rattfylleri','N');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (20,'Frihetsberövande','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (21,'Våld','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (22,'Kontroll person/fordon','N');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (23,'Anträffat gods','N');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (24,'Vapenlagen','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (25,'Fylleri/LOB','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (26,'Trafikbrott','N');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (27,'Knivlag','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (28,'Trafikhinder','N');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (29,'Ofredande/förargelse','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (30,'Djur skadat/omhändertaget','N');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (31,'Övrigt','N');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (32,'Mord','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (33,'Bråk','Y');



