DROP TABLE STOCKHOLM.CRIMES;
DROP TABLE STOCKHOLM.CRIMECATEGORY;
CREATE TABLE STOCKHOLM.CRIMECATEGORY(
ID INTEGER not null PRIMARY KEY,
CATEGORY VARCHAR(255),
ISRELEVANT VARCHAR(255)
);
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (1,'Bagagestöld,fickstöld','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (2,'Brott mot barn','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (3,'Bedrägeri','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (4,'Bilinbrott','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (5,'Bostadsinbrott','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (6,'Cykelstöld','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (7,'Dataintrång','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (8,'Djurstöld','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (9,'Fickstöld och bagagestöld','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (10,'Gromning','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (11,'Hatbrott','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (12,'Hedersrelaterade brott','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (13,'Hot','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (14,'Inbrott','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (15,'Investeringsbedrägeri','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (16,'Klotter','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (17,'Lärare - brott mot barn och unga','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (18,'Misshandel','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (19,'Motorfordon - inbrott, stulen, parkeringsskada','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (20,'Människohandel','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (21,'Näthat','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (22,'Olaga förföljelse','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (23,'Olaga hot','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (24,'Parkeringsskada','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (25,'Rån','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (26,'Sexualbrott','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (27,'Sexuella ändamål - människohandel','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (28,'Sexuellt ofredande','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (29,'Skadegörelse','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (30,'Stalkning','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (31,'Stöld','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (32,'Våldtäkt','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (33,'Bråk, slagsmål','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (34,'Olycka, olycksfall','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (35,'Försvunnen','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (36,'Trafikolycka','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (37,'Arbetsplatsolycka','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (38,'Brand','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (39,'Snatteri','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (40,'Narkotikabrott','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (41,'Rattfylleri','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (42,'Frihetsberövande','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (43,'Våld','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (44,'Kontroll person/fordon','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (45,'Anträffat gods','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (46,'Vapenlagen','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (47,'Fylleri/LOB','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (48,'Trafikbrott','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (49,'Knivlag','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (50,'Trafikhinder','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (51,'Detonation','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (52,'Ofredande/förargelse','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (53,'Djur skadat/omhändertaget','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (54,'Övrigt','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (55,'Sedlighetsbrott','Y');
INSERT INTO STOCKHOLM.CRIMECATEGORY VALUES (56,'Mord','Y');



